# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a4eedb5c4add108a9341a528f2fd3490838e384d113ca3baf7a4ac425072cfa0da1d48547327bd6a25cd4374ae1dfd9a30b6cd04148f2ef28672cdd6d6506fe

test:
  secret_key_base: a26f047f679457512ee4247033b2bf0a00da8dbfaa08dde0b71c06d2553ab2f871943a156e63498635590d5f3f167cf0367d811f4482fd136d6bccb6eed5e3d9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
